import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { TypeAnimation } from 'react-type-animation';
import Lottie from 'react-lottie'

import Header from '../components/Header';
import Footer from '../components/Footer';
import musicAnimation from '../images/music_animation.json'
import spotifyAnimation from '../images/spotify_animation.json'

function About() {
    return (
        <>
            <Header />
            <Container fluid className='mainBg'>
                <Row className='p-5'>
                    <Col>
                        <TypeAnimation
                            sequence={[
                                'Music is an integral part of our lives.',
                            ]}
                            wrapper='h1'
                            speed={50}
                            className='spotifyGreen mb-4'
                        />
                        <p>It is undeniable that music streaming platforms, such as Spotify, have revolutionized the way we consume and interact with music. However, despite the immense popularity and variability of today's music, understanding the attributes that make up the songs that top Spotify's charts still remains relatively unknown.</p>
                        <p><span className='spotifyGreenBg'>As such, this project aims to unravel the complexities behind these chart-toppers, shedding light on the multifaceted dynamics driving music trends in the digital age we live in today.</span></p>
                    </Col>
                    <Col>
                        <Lottie 
                            options={{
                                loop: true,
                                autoplay: true,
                                animationData: musicAnimation,
                                rendererSettings: {
                                    preserveAspectRatio: "xMidYMid slice"
                                }
                            }}
                            height={250}
                            width={250}
                        />
                    </Col>
                </Row>
                <hr />
                    <Row className='p-5'>
                        <Col>
                            <Lottie 
                                options={{
                                    loop: true,
                                    autoplay: true,
                                    animationData: spotifyAnimation,
                                    rendererSettings: {
                                        preserveAspectRatio: "xMidYMid slice"
                                    },
                                    speed: '0.5' 
                                }}
                                height={400}
                                width={400}
                            />
                        </Col>
                        <Col>
                            <TypeAnimation
                                sequence={[
                                    'Our Approach',
                                ]}
                                wrapper='h1'
                                speed={50}
                                className='spotifyGreen mb-4'
                            />
                            <p>Large amounts of data are generated by millions of Spotify users worldwide every day. By presenting this data in organised charts, industry stakeholders will not only be able to make informed decisions, but also be empowered to tailor their strategies and cater to their audience more effectively.</p>
                            <p><span className='spotifyGreenBg'>We will be analyzing the top 100 Spotify hits every year from 2010 to 2023 to identify any trends or patterns amongst chart-toppers.</span></p>
                            <p>We used the following datasets from Kaggle, collected using <a href='https://developer.spotify.com/documentation/web-api' target='_blank' rel="noreferrer" className='spotifyGreen'>Spotify's open API</a>:</p>
                            <ol>
                                <li>
                                    <a href='https://www.kaggle.com/datasets/josephinelsy/spotify-top-hit-playlist-2010-2022' target='_blank' rel="noreferrer" className='spotifyGreen'>Spotify Top Hit Playlist (2010-2022)</a>
                                </li>
                                <li>
                                <a href='https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023' target='_blank' rel="noreferrer" className='spotifyGreen'>Most Streamed Spotify Songs 2023</a>
                                </li>
                            </ol>
                            <p>We also utilised <a href='https://openai.com/chatgpt' target='_blank' rel="noreferrer" className='spotifyGreen'>ChatGPT</a> to generate additional information, such as artist gender and ethnicity.</p>
                        </Col>
                    </Row>
                <hr />
                <TypeAnimation
                    sequence={[
                        'Our Motivation',
                    ]}
                    wrapper='h1'
                    speed={50}
                    className='spotifyGreen text-center pt-5'
                />
                <Row className='pt-5 px-5'>
                    <Col>
                        <h3 className='spotifyGreen'>Industry Insight</h3>
                        <p>Insights gained from this analysis can provide valuable information for music industry professionals, allowing them to better understand audience preferences and trends.</p>
                    </Col>
                    <Col>
                        <h3 className='spotifyGreen'>Consumer Experience</h3>
                        <p>Understanding what makes a song popular allows streaming platforms to enhance their recommendation algorithms, thus providing users with a more personalized and enjoyable listening experience.</p>
                    </Col>
                    <Col>
                        <h3 className='spotifyGreen'>Marketing and Promotion</h3>
                        <p>Knowing the elements that contribute to a song's success can help marketers and promoters tailor their strategies to maximize the potential reach and impact of new releases.</p>
                    </Col>
                </Row>
                <Row className='p-5'>
                    <Col>
                        <h3 className='spotifyGreen'>Complexity</h3>
                        <p>The music industry is dynamic and influenced by numerous factors such as genre, artist popularity, production quality, and cultural trends. Deciphering the elements that contribute to a song's success requires analyzing a diverse range of data points, making it a multifaceted and intriguing problem.</p>
                    </Col>
                    <Col>
                        <h3 className='spotifyGreen'>Predictive Challenge</h3>
                        <p>Predicting future hit songs involves navigating the complexities of human taste and cultural evolution. It's not merely about identifying current trends but also anticipating how they might evolve and intersect in the future, presenting an engaging predictive challenge.</p>
                    </Col>
                    <Col>
                        <h3 className='spotifyGreen'>Cultural Significance</h3>
                        <p>Hit songs often reflect and shape cultural norms, attitudes, and identities. By studying the characteristics of past hits, researchers can gain insights into the cultural dynamics driving music consumption, offering a fascinating window into societal trends and values.</p>
                    </Col>
                </Row>
            </Container>
            <Footer />
        </>
    );
}

export default About;